#-------------------------------
# General Site Info

email: amy@amydepalma.com
url: "http://www.amydepalma.com" # the base hostname & protocol for your site

# Base SEO
seo:
    title: Amy DePalma | UI developer (and sometimes-designer) in Pittsburgh, PA
    description: Online portfolio of Amy DePalma, a UI developer (and sometimes-designer) in Pittsburgh, PA
    keywords: UI developer, UI designer, website developer, web design, freelance, pittsburgh, graphic design

#-------------------------------
#Google Analytics
google-analytics: UA-13163377-1

#-------------------------------
# Navigation
nav:
- {icon: 'fas fa-envelope', name: 'Contact', url: 'mailto:amy@amydepalma.com', target: '_blank'}
- {icon: 'fas fa-file-pdf', name: 'Resume', url: '/AmyDePalma_Resume.pdf', target: '_blank'}
- {icon: 'fab fa-linkedin', name: 'LinkedIn', url: 'https://www.linkedin.com/in/amydepalma', target: '_blank'}
- {icon: 'fab fa-codepen', name: 'Codepen', url: 'https://codepen.io/amydepalma/', target: '_blank'}

